name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true

version-resolver:
  major:
    labels: ['breaking-change', 'semver:major']
  minor:
    labels: ['feature', 'feat', 'enhancement', 'semver:minor']
  patch:
    labels: ['bug', 'fix', 'chore', 'refactor', 'docs', 'test', 'semver:patch']
  default: patch

categories:
  - title: '✨ Nové funkce'
    labels: ['feature', 'enhancement']
  - title: '🐛 Opravy chyb'
    labels: ['bug', 'fix']
  - title: '🧹 Refaktoring / Údržba'
    labels: ['refactor', 'chore', 'maintenance']
  - title: '📝 Dokumentace'
    labels: ['docs', 'documentation']
  - title: '🧪 Testy'
    labels: ['test', 'tests']
  - title: '⚠️ Breaking changes'
    labels: ['breaking-change', 'semver:major']

exclude-labels:
  - 'skip-changelog'

change-template: |
  - $TITLE (#$NUMBER) @$AUTHOR
    <details>
    <summary>Detail</summary>

    $BODY

    </details>
change-title-escapes: '\<*_&'

template: |
  ## Co je nového
  $CHANGES

  ---
  ## 📦 Technické
  - Verze: `v$RESOLVED_VERSION`
  - Předchozí tag: `$PREVIOUS_TAG`
  - Autoři: $CONTRIBUTORS
