name: Feature request
description: Návrh zlepšení nebo nové karty
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Popis co by se mělo zlepšit, návrh na přidání funkce.
  - type: textarea
    id: solution
    attributes:
      label: Návrh řešení
  - type: textarea
    id: extra
    attributes:
      label: Další kontext / mockup
