import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = __dirname + '/../package.json';
const outPath = __dirname + '/../src/version.ts';

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version || '0.0.0';
const buildDate = new Date().toISOString();

const banner = `// Auto-generated by scripts/generate-version.mjs — do not edit manually`;
const content = `${banner}
export const CARD_VERSION = "${version}";
export const BUILD_DATE = "${buildDate}";
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, 'utf8');
console.log('Generated src/version.ts with version', version);
