name: Release Drafter (main)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize, labeled, unlabeled, edited, closed]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       
          fetch-tags: true    
      - name: Update draft release for main
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          commitish: ${{ github.event.pull_request.base.ref || 'main' }}
          filter-by-commitish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
