name: Publish Draft (on tag)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish draft with Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
          tag: ${{ github.ref_name }}
          config-name: release-drafter.yml
          fetch-depth: 0       
          fetch-tags: true    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
